### ISSUE TITLE
Andes's "ideas"

### ISSUE THREAD

**Issue by skyn21prime** [Parlier-NJROTC/parlier-njrotc.github.io#23]
I think the website could improve if a feature were implemented where the background image drops down and becomes less transparent as you scroll. I think that the colors that were chosen look bad together and could be used in different areas.

**Comment by Cyborgnetical** [comment]
oki

**Comment by Cyborgnetical** [comment]
he suggested #474448 #2D232E #EDDDCF #534B52 #F1F0EA for colors

**Comment by Cyborgnetical** [comment]
Andres ideas implemented. Thank you for the colors they inspired me a lot down the line :D
