### ISSUE TITLE
Side Menus Loading Issue

### ISSUE THREAD

**Issue by Cyborgnetical** [Parlier-NJROTC/parlier-njrotc.github.io#33]
### Description
If the user has a slow internet connection, the side menus JavaScript fails to load properly causing the menus button to be unresponsive until the page is reloaded.

**Comment by skyn21prime** [comment]
Hey, I think this may help, Mkay?
https://stackoverflow.com/questions/76328391/clicking-menu-button-not-working-until-page-fully-loaded

**Comment by Cyborgnetical** [comment]
I found another solution!
https://css-tricks.com/off-canvas-menu-with-css-target/

**Comment by Cyborgnetical** [comment]
requries a complete rewrite of all file paths, will take a while. removing jekyll

**Comment by skyn21prime** [comment]
-Marked as Fixed-
