### ISSUE TITLE
Suggestion by luis.

### ISSUE THREAD

**Issue by Cyborgnetical** [Parlier-NJROTC/parlier-njrotc.github.io#39]
Make a tool to create a preview to how the ribbions should be arranged.

**Comment by Cyborgnetical** [comment]
and add scholarships plus njrotc benefits

**Comment by skyn21prime** [comment]
you forgot to include le link

**Comment by skyn21prime** [comment]
It has to be changed to a Whole different language

**Comment by skyn21prime** [comment]
It is "Done"
